dataset_path = "datasets/time-simple"
output_dataset_path = "datasets/dataset_fish"

[model]
model_type = "openai"
base_url = "http://localhost:3000/v1"
model_id = "gpt-4o-mini-tts"
voice = "sky"
requests_per_minute = 250

[transcriber]
model_type = "whisper-cpp"
base_url = "http://localhost:5000"
model_id = "whisper-1"
# TODO see if we can get more requests per minute
requests_per_second = -1
